version: '3'
services:
  pigallery2:
    image: bpatrik/pigallery2:latest
    container_name: pigallery2
    environment:
      - NODE_ENV=production
    volumes:
      - "./config:/app/data/config"
      - "./db:/app/data/db"
      - "./images:/app/data/images"
      - "./tmp:/app/data/tmp"
    ports:
      - 8888:80
    restart: always

volumes:
  db-data:
